// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAPI.Data;

namespace WebAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20210222144513_CreateDataBase")]
    partial class CreateDataBase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebAPI.Models.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("CountryId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("CountryName");

                    b.Property<long>("Population")
                        .HasColumnType("bigint")
                        .HasColumnName("Population");

                    b.HasKey("CountryId");

                    b.ToTable("Country");

                    b.HasData(
                        new
                        {
                            CountryId = 1,
                            Name = "Sfax",
                            Population = 1000L
                        },
                        new
                        {
                            CountryId = 2,
                            Name = "Sousse",
                            Population = 1000L
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("DepartmentId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("DepartmentName");

                    b.HasKey("DepartmentId");

                    b.ToTable("Department");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = ".Net"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "NodeJs"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Flutter"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "React"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "WordPress"
                        },
                        new
                        {
                            DepartmentId = 6,
                            DepartmentName = "Prestashop"
                        },
                        new
                        {
                            DepartmentId = 7,
                            DepartmentName = "RH"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("EmployeeId")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CountryID")
                        .HasColumnType("int");

                    b.Property<string>("DateOfJoining")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("EmployeeName");

                    b.Property<string>("PhotoFileName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("CountryID");

                    b.HasIndex("DepartmentId");

                    b.ToTable("Employee");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            EmployeeName = "Sofien"
                        },
                        new
                        {
                            EmployeeId = 2,
                            EmployeeName = "Ahmed"
                        },
                        new
                        {
                            EmployeeId = 3,
                            EmployeeName = "Khadija"
                        },
                        new
                        {
                            EmployeeId = 4,
                            EmployeeName = "Mahmoud"
                        },
                        new
                        {
                            EmployeeId = 5,
                            EmployeeName = "Majdi"
                        },
                        new
                        {
                            EmployeeId = 6,
                            EmployeeName = "Haitham"
                        },
                        new
                        {
                            EmployeeId = 7,
                            EmployeeName = "Maryam"
                        });
                });

            modelBuilder.Entity("WebAPI.Models.Employee", b =>
                {
                    b.HasOne("WebAPI.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryID");

                    b.HasOne("WebAPI.Models.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId");

                    b.Navigation("Country");

                    b.Navigation("Department");
                });
#pragma warning restore 612, 618
        }
    }
}
